-- CREATE TABLE currentWeather(
-- id INTEGER NOT NULL PRIMARY KEY ,
--   city TEXT NOT NULL,
--   temperature DOUBLE NOT NULL,
--   humidity DOUBLE NOT NULL,
--   status TEXT NOT NULL,
--   lat DOUBLE NOT NULL,
--   lon DOUBLE NOT NULL,
--   sunrise INT NOT NULL,
--   sunset INT NOT NULL,
--   ctime INT NOT NULL,
--   year INT NOT NULL,
--   month INT NOT NULL,
--   date INT NOT NULL,
--   hour INT NOT NULL,
--   min INT NOT NULL
-- );
SELECT * FROM currentWeather;